stages:
  - test
  - build
  - deploy

# --- ÉTAPE 1 : TESTS (BACKEND & FRONTEND) ---

test_backend:
  stage: test
  image: python:3.10
  script:
    - cd backend
    - pip install -r requirements.txt
    - python -m py_compile main.py # Vérifie les erreurs de syntaxe Python

test_frontend:
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm install  # Installe les dépendances (Vue.js, Axios, etc.)
    - npm run build # Tente de compiler le projet pour la production
    - echo "Le Frontend a été compilé avec succès (aucun bug détecté)."

# --- ÉTAPE 2 : BUILD DES IMAGES DOCKER ---

build_images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t catalogue-backend:v2 ./backend
    - docker build -t catalogue-frontend:latest ./frontend

# --- ÉTAPE 3 : DÉPLOIEMENT ---

deploy_to_k8s:
  stage: deploy
  image: alpine/k8s:1.29.2
  script:
    - echo "Validation des fichiers YAML de déploiement..."
    - ls k8s/
    - echo "fichiers pret pour deploiement"
  environment:
    name: production
    url: http://192.168.33.10:8080
