apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort 
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Le port interne du conteneur Nginx
      targetPort: 80
      nodePort: 30080   # Le port extérieur que tu taperas dans ton navigateur
